#ifndef TACTILE_STREAM_PROTOCOL_H
#define TACTILE_STREAM_PROTOCOL_H

#include <stdint.h>

/* MCU-PC records are independent from the sensor's A5...5A protocol. */
#define TACTILE_STREAM_SYNC_0                 0xD3U
#define TACTILE_STREAM_SYNC_1                 0x5CU
#define TACTILE_STREAM_VERSION                0x01U
#define TACTILE_STREAM_HEADER_SIZE              8U
#define TACTILE_STREAM_CRC_SIZE                 2U

#define TACTILE_STREAM_RECORD_DATA            0x01U
#define TACTILE_STREAM_RECORD_STATUS          0x02U
#define TACTILE_STREAM_SYSTEM_PORT_ID         0xFFU

#define TACTILE_STREAM_PORT_COUNT              11U
#define TACTILE_STREAM_DMA_BUFFER_SIZE       1024U
#define TACTILE_STREAM_DMA_HALF_SIZE          512U

#define TACTILE_STREAM_PORT_CN1_USART1          0U
#define TACTILE_STREAM_PORT_CN2_USART2          1U
#define TACTILE_STREAM_PORT_CN3_USART3          2U
#define TACTILE_STREAM_PORT_CN4_UART4           3U
#define TACTILE_STREAM_PORT_CN5_UART5           4U
#define TACTILE_STREAM_PORT_CN6_USART6          5U
#define TACTILE_STREAM_PORT_CN7_UART7           6U
#define TACTILE_STREAM_PORT_CN8_UART9           7U
#define TACTILE_STREAM_PORT_CN9_USART10         8U
#define TACTILE_STREAM_PORT_CN10_USART11        9U
#define TACTILE_STREAM_PORT_CN11_UART12        10U

/* 状态包包含各路诊断计数、USB 队列历史峰值与实时待发字节数。 */
#define TACTILE_STREAM_STATUS_VERSION         0x04U
#define TACTILE_STREAM_STATUS_HEADER_SIZE        4U
#define TACTILE_STREAM_STATUS_COUNTER_SIZE       4U
#define TACTILE_STREAM_STATUS_COUNTER_ARRAY_SIZE \
  (TACTILE_STREAM_PORT_COUNT * TACTILE_STREAM_STATUS_COUNTER_SIZE)
#define TACTILE_STREAM_STATUS_OVERFLOW_OFFSET    TACTILE_STREAM_STATUS_HEADER_SIZE
#define TACTILE_STREAM_STATUS_ERROR_COUNT_OFFSET \
  (TACTILE_STREAM_STATUS_OVERFLOW_OFFSET + TACTILE_STREAM_STATUS_COUNTER_ARRAY_SIZE)
#define TACTILE_STREAM_STATUS_RX_HALF_OFFSET \
  (TACTILE_STREAM_STATUS_ERROR_COUNT_OFFSET + TACTILE_STREAM_STATUS_COUNTER_ARRAY_SIZE)
#define TACTILE_STREAM_STATUS_LAST_ERROR_OFFSET \
  (TACTILE_STREAM_STATUS_RX_HALF_OFFSET + TACTILE_STREAM_STATUS_COUNTER_ARRAY_SIZE)
#define TACTILE_STREAM_STATUS_USB_HIGH_WATER_OFFSET \
  (TACTILE_STREAM_STATUS_LAST_ERROR_OFFSET + TACTILE_STREAM_STATUS_COUNTER_ARRAY_SIZE)
#define TACTILE_STREAM_STATUS_DMA_ERROR_OFFSET \
  (TACTILE_STREAM_STATUS_USB_HIGH_WATER_OFFSET + TACTILE_STREAM_STATUS_COUNTER_SIZE)
#define TACTILE_STREAM_STATUS_USB_PENDING_OFFSET \
  (TACTILE_STREAM_STATUS_DMA_ERROR_OFFSET + TACTILE_STREAM_STATUS_COUNTER_ARRAY_SIZE)
#define TACTILE_STREAM_STATUS_DROP_COUNT_OFFSET \
  (TACTILE_STREAM_STATUS_USB_PENDING_OFFSET + TACTILE_STREAM_STATUS_COUNTER_SIZE)
#define TACTILE_STREAM_STATUS_PAYLOAD_SIZE \
  (TACTILE_STREAM_STATUS_DROP_COUNT_OFFSET + TACTILE_STREAM_STATUS_COUNTER_SIZE)

#endif /* TACTILE_STREAM_PROTOCOL_H */
